### ISSUE TITLE
[3pt]  - Add all items counter on the Homepage - Student A

### ISSUE THREAD

**Issue by gvgesanto2** [gvgesanto2/microverse-js-capstone#6]
Even if the API gives you the number of items, you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Homepgae.

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/175609759-8e358075-bed3-4c32-9db0-159ae655c5c4.png)
Created the Number of Shows function, using the API Data List
