### ISSUE TITLE
[3pt]  - Create feature: add  new like - Student A

### ISSUE THREAD

**Issue by gvgesanto2** [gvgesanto2/microverse-js-capstone#9]
When the user clicks on the Like button of an item (on Homepage), the interaction is recorded in the Involvement API and the screen is updated.

**Comment by David-Verde** [comment]
![image](https://user-images.githubusercontent.com/99683363/175657308-c6b98e16-c7ea-4fc9-9dba-fce790cb7011.png)
created the add likes function using API cloud function, add some hover on heart too.
